name: OME  Website
markdown: kramdown

url: ''
repository: openmicroscopy/www.openmicroscopy.org
baseurl: /www.openmicroscopy.org

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 10
paginate_path: "/announcements/page:num/"

future: true

bf:
 version: 5.9.1

omero:
 version: 5.4.7
 build: b93

omecommoncpp:
  version: 5.5.0

omemodel:
  version: 5.6.1

omeqtwidgets:
 version: 5.4.3
 
omefiles:
 version: 0.5.0
 build: 25

omecmakesuperbuild:
 version: 0.5.0
