name: OME  Website
markdown: kramdown

url: ''
repository: openmicroscopy/www.openmicroscopy.org
baseurl: /www.openmicroscopy.org

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 10
paginate_path: "/announcements/page:num/"

future: true

bf:
 version: 6.3.1

omero:
 version: 5.6.0
 majorversion: 5.6
 build: b138
 insight:
  version: 5.5.8
 matlab:
  version: 5.5.3

omecommoncpp:
  version: 5.5.0

omemodel:
  version: 6.0.0

omeqtwidgets:
 version: 5.4.3

omefiles:
 version: 0.5.0
 build: 25

omecmakesuperbuild:
 version: 0.5.0

sitemap:
    filename: "/sitemap.xml"
    exclude:
    include_posts:
    change_frequency_name: "change_frequency"
    priority_name: "priority"
