name: OME  Website
markdown: kramdown

baseurl: /www.openmicroscopy.org

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/community/news/page:num/"

bf:
 version: 5.5.2

omero:
 version: 5.3.3
 build: b63

omecommoncpp:
  version: 5.4.0

omemodel:
  version: 5.5.1

omeqtwidgets:
 version: 5.4.0
 
omefiles:
 version: 0.3.2
 build: 22

omecmakesuperbuild:
 version: 0.3.2
