name: OME  Website
markdown: kramdown

baseurl: /www.openmicroscopy.org

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/announcements/page:num/"

future: true

bf:
 version: 5.7.1

omero:
 version: 5.3.4
 build: b69

omecommoncpp:
  version: 5.4.2

omemodel:
  version: 5.5.7

omeqtwidgets:
 version: 5.4.2
 
omefiles:
 version: 0.4.0
 build: 24

omecmakesuperbuild:
 version: 0.4.0
