name: OME  Website
markdown: kramdown

baseurl: /www.openmicroscopy.org

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/announcements/page:num/"

future: true

bf:
 version: 5.7.2

omero:
 version: 5.4.1
 build: b75

omecommoncpp:
  version: 5.5.0

omemodel:
  version: 5.6.0

omeqtwidgets:
 version: 5.4.3
 
omefiles:
 version: 0.5.0
 build: 25

omecmakesuperbuild:
 version: 0.5.0
